version: '3.8'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    networks:
      - net

  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    volumes:
      - ./php-fpm/slim_app:/var/www/slim_app
    networks:
      - net

  composer-cmd:
    image: composer:2.5.8
    volumes:
      - ./php-fpm/slim_app:/app

networks:
  net:
