version: '3.8'

services:

  https-portalk:
    build: ./https-portal
    container_name: https-portal
    volumes:
        - ./https-portal/ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: 'localhost -> http://host.docker.internal:8080'
      STAGE: local
      # FORCE_RENEW: 'true'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - net

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    networks:
      - net

  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    volumes:
      - ./php-fpm/slim_app:/var/www/slim_app
    networks:
      - net

  composer-cmd:
    image: composer:2.5.8
    volumes:
      - ./php-fpm/slim_app:/app
    profiles:
      - tools

  redis:
    build: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - net

  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - net

  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - "./mariadb/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - net

  migrate-cmd:
    image: migrate/migrate:v4.16.2
    container_name: migrate-cmd
    volumes:
      - ./migrate/sql:/migrations
    networks:
      - net
    profiles:
      - tools

networks:
  net:
